// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4qqwHqqNstnaIxwgzuAwmdR0K8BL741Y',
    appId: '1:183882563100:web:7c772b8e1d2b10ae1929d9',
    messagingSenderId: '183882563100',
    projectId: 'modul3-73acf',
    authDomain: 'modul3-73acf.firebaseapp.com',
    storageBucket: 'modul3-73acf.appspot.com',
    measurementId: 'G-3SL6FCGX6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhjQgp2wsKrOQkAIjToc-UwHV7hI1IEVE',
    appId: '1:183882563100:android:f8a7cdab33609beb1929d9',
    messagingSenderId: '183882563100',
    projectId: 'modul3-73acf',
    storageBucket: 'modul3-73acf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-typeV6gDIwOKZZ7-U7HRoFSP8FWJw5E',
    appId: '1:183882563100:ios:1453ce2964b97ff31929d9',
    messagingSenderId: '183882563100',
    projectId: 'modul3-73acf',
    storageBucket: 'modul3-73acf.appspot.com',
    iosBundleId: 'sulthanariq17webmail.umm.ac.id.tugas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-typeV6gDIwOKZZ7-U7HRoFSP8FWJw5E',
    appId: '1:183882563100:ios:1453ce2964b97ff31929d9',
    messagingSenderId: '183882563100',
    projectId: 'modul3-73acf',
    storageBucket: 'modul3-73acf.appspot.com',
    iosBundleId: 'sulthanariq17webmail.umm.ac.id.tugas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4qqwHqqNstnaIxwgzuAwmdR0K8BL741Y',
    appId: '1:183882563100:web:8af8a34748a709991929d9',
    messagingSenderId: '183882563100',
    projectId: 'modul3-73acf',
    authDomain: 'modul3-73acf.firebaseapp.com',
    storageBucket: 'modul3-73acf.appspot.com',
    measurementId: 'G-50EW5B7M4V',
  );
}
